<?php 
namespace App;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Game extends Model{

    public $timestamps=false;
    public $table = "game";
    protected $primaryKey = 'id';
    protected $fillable = ['id','user_id','score'];

public function users(){ 
    return $this->hasMany('App\User'); 
}

}