<?php 
namespace App;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Questions extends Model{
    public $timestamps=false;
    public $table = "questions";
    protected $primaryKey = 'id';
    protected $fillable = ['id','questionname','answer_id'];
public function levels(){ 
    return $this->belongsTo('App\Models\Levels');
 }
}