<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateQuestionss extends Migration{
	public function up(){ 
 		Schema::create('questions', function (Blueprint $table) { 
			$table->engine = 'InnoDB';
			$table->bigIncrements('id');
			$table->text('questionname',300);
		});
 	} 
	public function down(){
		Schema::dropIfExists('questions');
	} 
}